name: Jekyll site test builder

on:
  pull_request:

jobs:
  build_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:stable /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future --config _config.yml"
