name: Jekyll site CI

on:
  push:
    branches:    
      - master   

jobs:
  build_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set proper permission
      run: |
        chmod 777 ${{ github.workspace }}
    - name: Build site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:stable /bin/bash -c "chmod +x ci-build.sh && ./ci-build.sh ${{ github.sha }} ${{ github.run_id }}"
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
        
  deploy:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: build
    - name: "Prepare SSH key and known hosts"
      # https://github.com/symfony/cli/issues/227#issuecomment-601680974
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    - name: Create and extract to working directory
      run: |
        mkdir wrktmp
        tar -xzvf build/build.tar.gz -C wrktmp/
    - name: Run deploy script
      run: |
        cd wrktmp
        scp -r . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.WEBPATH }}/
