name: Jekyll site CI

on:
  push:
    branches:    
      - master   

jobs:
  build_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:stable /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future --config _config.yml && mkdir build && tar -czvf build/build.tar.gz -C _site ."
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
        
  deploy:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: build
    - name: "Prepare SSH key and known hosts"
      # https://github.com/symfony/cli/issues/227#issuecomment-601680974
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    - name: Run deploy script
      run: |
        scp build/build.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.WEBPATH }}/
        ssh -o StrictHostKeyChecking=yes ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -c "mkdir ${{ secrets.WEBPATH }}/build; tar -xvf ${{ secrets.WEBPATH }}/build.tar.gz -C ${{ secrets.WEBPATH }}/build; rm -Rf ${{ secrets.WEBPATH }}/site; mv ${{ secrets.WEBPATH }}/build ${{ secrets.WEBPATH }}/site; rm ${{ secrets.WEBPATH }}/build.tar.gz"'